name: qr_code_scanner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.6     # ✅ include the splash package
  path_provider: ^2.1.5
  qr_code_scanner_plus: ^2.0.10+1
  qr_flutter: ^4.1.0
  share_plus: ^11.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1   # ✅ added icon generator

flutter:
  uses-material-design: true
  assets:
    - assets/modern/playstore.png        # ✅ used for splash and icon

# 🔧 Splash screen config
flutter_native_splash:
  color: "#ffffff"                 
  image: assets/modern/playstore.png
  android: true
  ios: true
  web: false
  android_12:
    image: assets/modern/playstore.png
    color: "#ffffff"
    icon_background_color: "#ffffff"

# 🎨 App icon config
flutter_icons:
  android: true
  ios: true
  image_path: assets/light/splash_logo.png
